language: python
python:
  - "3.6"

services:
  - docker

git:
  submodules: false

install:
  - make dep

script:
  - make checkformat

deploy:
  - provider: script
    script: make image docker-push
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = "false" # we don't want to push the new image already at pull request but wait until it's merged

deploy:
  - provider: script
    script: make image docker-push-dev
    on:
      branch: dev
      condition: $TRAVIS_PULL_REQUEST = "false"